version: "3.7"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresteddy
      - POSTGRES_DB=postgres-db
    network_mode: host
  back:
    depends_on:
      - postgres-db
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 3000:3000
    network_mode: host
    volumes:
      - ./back:/usr/back
    environment:
      - PORT=3000
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgresteddy
      - DB_DATABASE=postgres
  front:
    depends_on:
      - back
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    network_mode: host
    volumes:
      - ./front:/usr/front
    environment:
      - VITE_BASE_API_URL=http://localhost:3000