version: "3.7"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresteddy
      - POSTGRES_DB=postgres-db
    networks:
      - app-network
  back:
    depends_on:
      - postgres-db
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: back
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      - PORT=3000
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgresteddy
      - DB_DATABASE=postgres
    # volumes:
    #   - ./back:/usr/back
  front:
    depends_on:
      - back
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 3200:3200
    networks:
      - app-network
    environment:
      - VITE_BASE_API_URL=http://localhost:3000
    # volumes:
    #   - ./front:/usr/front
networks:
  app-network:
    driver: bridge