name: "Runing tests and deploy"
on:
  push:
    branches:
      - main
    paths:
      - "back/**"
jobs:
  tests:
    name: "Running tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout files"
        uses: "actions/checkout@v4"

      - name: "Node version"
        uses: actions/setup-node@v4
        with:
          node-version: "node"

      - run: npm ci
        working-directory: back

      - run: npm run test
        working-directory: back

  build-image:
    needs: tests
    name: "Build Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4

      - name: "Login Docker Hub"
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        working-directory: back

      - name: "Build docker image"
        run: docker build -t johnatanso/back-teddy:latest -f Dockerfile .
        working-directory: back

      - name: "Push image to Docker Hub"
        run: docker push johnatanso/back-teddy:latest
        working-directory: back

  deploy-app:
    needs: build-image
    name: "Deploy aplication"
    runs-on: self-hosted

    steps:
      - name: "Login Docker Hub"
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: "Removing old container"
        run: docker rm -f back-teddy

      - name: "Pull image from Docker Hub"
        run: docker pull johnatanso/back-teddy:latest

      - name: "Run imagem"
        run: docker run -d --network host -p 3000:3000 --name back-teddy -e DB_HOST=postgres-db.ctcme24kaukv.us-east-1.rds.amazonaws.com -e DB_PORT=5432 -e DB_USERNAME=postgres -e DB_DATABASE=postgres-db -e DB_PASSWORD=postgresteddy --restart always johnatanso/back-teddy:latest
